# Generated by Django 4.2.4 on 2023-09-04 17:12

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("clipper", "0003_taggedclip_alter_clip_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clip",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.DeleteModel(
            name="TaggedClip",
        ),
    ]
